import React, { useState, useEffect, useRef } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Box,
  Typography,
  Paper,
  CircularProgress,
  Alert
} from '@mui/material';
import { QrCode as QrCodeIcon, Print as PrintIcon, Download as DownloadIcon } from '@mui/icons-material';
import QRCode from 'qrcode.react';
import { studentAPI } from '../services/api';
import { toast } from 'react-toastify';

const QRCodeDisplay = ({ outpassId, outpassData, open, onClose }) => {
  const [outpass, setOutpass] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const qrRef = useRef();

  useEffect(() => {
    if (open) {
      if (outpassData) {
        // Use provided outpass data
        setOutpass(outpassData);
        setLoading(false);
        setError('');
      } else if (outpassId) {
        // Fetch outpass details if only ID is provided
        fetchOutpassDetails();
      }
    }
  }, [open, outpassId, outpassData]);

  const fetchOutpassDetails = async () => {
    setLoading(true);
    setError('');

    try {
      const response = await studentAPI.getOutpassDetails(outpassId);
      setOutpass(response.data.outpass);
    } catch (error) {
      setError('Failed to load outpass details');
      toast.error('Failed to load outpass details');
    } finally {
      setLoading(false);
    }
  };

  const generateQRData = () => {
    if (outpass?.qr_code && outpass.qr_code.startsWith('data:image')) {
      return JSON.stringify({
        outpass_id: outpass.id,
        student_id: outpass.student_id,
        student_name: outpass.student_name,
        from_date: outpass.from_date,
        to_date: outpass.to_date,
        status: outpass.status,
        timestamp: new Date().toISOString()
      });
    }
    
    if (outpass?.qr_code && outpass.qr_code.length < 1000) {
      return outpass.qr_code;
    }
    
    return JSON.stringify({
      outpass_id: outpass?.id || 'unknown',
      student_id: outpass?.student_id || 'unknown',
      student_name: outpass?.student_name || 'unknown',
      from_date: outpass?.from_date || 'unknown',
      to_date: outpass?.to_date || 'unknown',
      status: outpass?.status || 'unknown',
      timestamp: new Date().toISOString()
    });
  };

  const handleDownload = () => {
    if (outpass?.qr_code && outpass.qr_code.startsWith('data:image')) {
      // Download the base64 image directly
      const link = document.createElement('a');
      link.href = outpass.qr_code;
      link.download = `outpass-qr-${outpass.id || 'unknown'}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } else if (qrRef.current) {
      // Download the QRCode generated by qrcode.react (SVG or Canvas)
      // Try SVG first
      const svg = qrRef.current.querySelector('svg');
      if (svg) {
        const serializer = new XMLSerializer();
        const svgString = serializer.serializeToString(svg);
        const canvas = document.createElement('canvas');
        const img = new window.Image();
        img.onload = function () {
          canvas.width = img.width;
          canvas.height = img.height;
          const ctx = canvas.getContext('2d');
          ctx.drawImage(img, 0, 0);
          const pngUrl = canvas.toDataURL('image/png');
          const link = document.createElement('a');
          link.href = pngUrl;
          link.download = `outpass-qr-${outpass?.id || 'unknown'}.png`;
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
        };
        img.src = 'data:image/svg+xml;base64,' + window.btoa(unescape(encodeURIComponent(svgString)));
      } else {
        // If not SVG, try Canvas
        const canvas = qrRef.current.querySelector('canvas');
        if (canvas) {
          const pngUrl = canvas.toDataURL('image/png');
          const link = document.createElement('a');
          link.href = pngUrl;
          link.download = `outpass-qr-${outpass?.id || 'unknown'}.png`;
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
        }
      }
    }
  };

  if (!open) return null;

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <DialogTitle>
        <Box display="flex" alignItems="center">
          <QrCodeIcon sx={{ mr: 1 }} />
          Outpass QR Code
        </Box>
      </DialogTitle>
      
      <DialogContent>
        {loading ? (
          <Box display="flex" justifyContent="center" alignItems="center" minHeight="200px">
            <CircularProgress />
          </Box>
        ) : error ? (
          <Alert severity="error">{error}</Alert>
        ) : outpass ? (
          <Box>
            <Paper elevation={3} sx={{ p: 3, textAlign: 'center' }}>
              <Box ref={qrRef}>
                {/* Show only one QR code - either the original image or generated QR */}
                {outpass.qr_code && outpass.qr_code.startsWith('data:image') ? (
                  // If it's a base64 image, display it directly
                  <img 
                    src={outpass.qr_code} 
                    alt="QR Code" 
                    style={{ 
                      width: '200px', 
                      height: '200px',
                      border: '1px solid #ddd',
                      borderRadius: '8px'
                    }} 
                  />
                ) : (
                  // Otherwise, generate a QR code from the data
                  <QRCode
                    value={generateQRData()}
                    size={200}
                    level="H"
                    includeMargin={true}
                  />
                )}
              </Box>
            </Paper>
            
            <Typography variant="h6" sx={{ mt: 2, mb: 1 }}>
              {outpass.student_name}
            </Typography>
            
            <Typography variant="body2" color="textSecondary" gutterBottom>
              <strong>From:</strong> {outpass.from_date} {outpass.from_time}
            </Typography>
            
            <Typography variant="body2" color="textSecondary" gutterBottom>
              <strong>To:</strong> {outpass.to_date} {outpass.to_time}
            </Typography>
            
            <Typography variant="body2" color="textSecondary" gutterBottom>
              <strong>Reason:</strong> {outpass.reason}
            </Typography>
            
            {outpass.qr_expires_at && (
              <Typography variant="body2" color="textSecondary" gutterBottom>
                <strong>Valid Until:</strong> {outpass.qr_expires_at}
              </Typography>
            )}
            
            <Alert severity="info" sx={{ mt: 2 }}>
              Show this QR code to the security guard when leaving and returning to the hostel.
            </Alert>
          </Box>
        ) : (
          <Alert severity="info">No outpass data available.</Alert>
        )}
      </DialogContent>
      
      <DialogActions>
        <Button
          variant="outlined"
          startIcon={<DownloadIcon />}
          onClick={handleDownload}
        >
          Download QR Code
        </Button>
        <Button onClick={onClose} variant="contained">
          Close
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default QRCodeDisplay;
